import React, {useState} from 'react';
import {parseRunnerConfig, type RunnerConfig} from '../shared/runner-config';

export function ConnectApp({disabled,onConnect}:{disabled:boolean;onConnect:(config:RunnerConfig)=>void}){
 const [fields,setFields]=useState({appUrl:'http://127.0.0.1:3000',port:'4468',path:'/api/generate',send:'[data-testid="send"]',cancel:'[data-testid="cancel"]',response:'[data-testid="response"]',promptSelector:'',prompt:'Suggest a title for my weekend project',evidence:'[data-testid="events"]',evidenceText:'Stream ended',forbidden:'Weekend Atlas'});
 const [pending,setPending]=useState(false);const [message,setMessage]=useState('');const [checks,setChecks]=useState<{name:string;ok:boolean;message:string}[]>([]);
 const build=()=>parseRunnerConfig({version:1,name:'Local app cancellation',appUrl:fields.appUrl,
  proxy:{port:Number(fields.port),path:fields.path,scenario:{version:1,id:'cancel-late-result',prompt:fields.prompt,cancelAtMs:700,observeUntilMs:1800,events:[{atMs:100,type:'text',text:'A possible title is '},{atMs:1100,type:'text',text:fields.forbidden},{atMs:1300,type:'complete'}],assertion:{type:'textAbsentAfterCancel',text:fields.forbidden}}},
  setup:fields.promptSelector?[{atMs:0,type:'fill',selector:fields.promptSelector,value:fields.prompt}]:[],actions:[{atMs:0,type:'click',selector:fields.send},{atMs:700,type:'click',selector:fields.cancel}],observeUntilMs:2200,
  assertions:[{type:'textAbsent',selector:fields.response,text:fields.forbidden,fromMs:700}],evidence:[{selector:fields.evidence,text:fields.evidenceText}]});
 const submit=async(check:boolean)=>{setPending(true);setMessage('');setChecks([]);try{const config=build();const reply=await fetch(`/api/runner/${check?'check':'setup'}`,{method:'POST',headers:{'Content-Type':'application/json','X-Agent-Timeline':'1'},body:JSON.stringify(config)});const data=await reply.json();if(!reply.ok)throw Error(data.error);if(check)setChecks(data);else{onConnect(parseRunnerConfig(data));setMessage('Configuration loaded below. Review routing, then choose Run scenario. Export runner config to save it; this setup is held in server memory only.')}}catch(error){setMessage(String(error))}finally{setPending(false)}};
 const labels:Record<keyof typeof fields,string>={appUrl:'Local app URL',port:'Proxy port',path:'Streaming endpoint path',send:'Send button selector',cancel:'Cancel button selector',response:'Response container selector',promptSelector:'Prompt input selector (optional)',prompt:'Test prompt',evidence:'Delivery log selector',evidenceText:'Delivery evidence text',forbidden:'Late text that must stay absent'};
 return <section className="panel"><h2>Connect your app</h2><p>Configure a local cancellation test without editing JSON. Your app opens in a fresh test browser; your current browser login is not reused.</p>
 <fieldset disabled={disabled||pending} className="connect-fields"><legend>App and cancellation test</legend>{(Object.keys(fields) as (keyof typeof fields)[]).map(key=><label key={key}>{labels[key]}<input type={key==='port'?'number':'text'} value={fields[key]} onChange={e=>{setFields({...fields,[key]:e.target.value});setChecks([]);setMessage('')}}/></label>)}</fieldset>
 <p>Route your app’s development POST endpoint to <code>http://127.0.0.1:{fields.port}{fields.path}</code>. The runner starts this proxy for each test. This form does not change your app’s routing.</p>
 <p>Simulation sends Agent Timeline NDJSON, not OpenAI/SSE or an automatic SDK adapter. Your app must understand this protocol; see <a href="https://github.com/Agent-Timeline/agent-timeline/blob/main/docs/PROVIDER.md">provider integration</a>. For an existing local upstream protocol, use the CLI setup or full JSON editor.</p>
 <p>Send runs at 0 ms, Cancel at 700 ms, and the late text arrives 1100 ms after the provider receives the request. Observation ends at 2200 ms. Edit timings in the timeline after loading. Delivery evidence must prove the stream arrived, not merely that Send was clicked.</p>
 <div className="actions"><button disabled={disabled||pending} onClick={()=>void submit(true)}>{pending?'Working…':'Check connection'}</button><button className="primary" disabled={disabled||pending} onClick={()=>void submit(false)}>Use this configuration</button></div>
 <div aria-live="polite">{message&&<p>{message}</p>}{checks.map(check=><p key={check.name}>{check.ok?'OK':'CHECK'} · {check.name}: {check.message}</p>)}</div>
 <p>Connection checks only test app reachability and a temporary proxy health endpoint. They do not click controls or verify selectors, stream compatibility, or routing.</p>
 <p>After reviewing the loaded scenario, choose <strong>Export runner config</strong> and save the downloaded file in your local checkout. Run the same configuration from that checkout:</p><pre>npm run run:app -- --config agent-timeline.config.json</pre><p>Keep private configurations and captured reports out of public commits.</p>
 </section>;
}
