import { test, expect } from '@playwright/test';
test('recovery inspection restores recorded state without changing the verdict', async ({ page }) => {
  await page.goto('/');
  await page.getByLabel('Workbench scenario').selectOption('recovery');
  await page.getByRole('button', { name: 'Run scenario', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Inspect replay', exact: true })).toHaveCount(0);
  await expect(page.getByTestId('gallery-verdict')).toContainText('PASS:');
  await page.getByRole('button', { name: 'Inspect replay', exact: true }).click();
  const slider = page.getByRole('slider', { name: 'Inspection time', exact: true });
  await slider.fill('700');
  await expect(page.getByTestId('inspection-output')).toHaveText('Draft');
  await expect(page.getByTestId('inspection-status')).toHaveText('Disconnected');
  await expect(page.getByTestId('inspection-events')).not.toContainText('Connection restored');
  const playhead = page.getByRole('slider', { name: 'Replay playhead', exact: true }).first();
  await playhead.focus();
  await page.keyboard.press('Home');
  await expect(page.getByTestId('inspection-output')).toBeEmpty();
  await page.keyboard.press('End');
  await expect(page.getByTestId('inspection-output')).toHaveText('Draft recovered');
  const box = await playhead.boundingBox();
  const lane = await page.locator('.recovery-lane').first().boundingBox();
  if (!box || !lane) throw new Error('Missing timeline geometry');
  await page.mouse.move(box.x + 1, box.y + 15);
  await page.mouse.down();
  await page.mouse.move(lane.x + lane.width * 700 / 1800, box.y + 15);
  await page.mouse.up();
  await expect(page.getByTestId('inspection-status')).toHaveText('Disconnected');
  await expect(page.getByTestId('gallery-verdict')).toContainText('PASS:');
  await expect(page.getByTestId('gallery-output')).toHaveText('Draft recovered');
  await page.getByRole('button', { name: 'Reset', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Inspect replay' })).toHaveCount(0);
});
